version: "3"
services:

    mariadb:
      image: mariadb:10.1
      container_name: mariadb-api
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=apidb
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "8181:3306"
      networks:
        api-network:
          ipv4_address: 10.33.0.30

    webserver:
      image: nginx:alpine
      container_name: webserver-api
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8300:80"
      networks:
        api-network:
          ipv4_address: 10.33.0.20

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm-api
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.
      networks:
        api-network:
          ipv4_address: 10.33.0.10

networks:

   api-network:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.33.0.0/24
