#index:
#    path: /
#    controller: App\Controller\DefaultController::index

movies:
    type: rest
    resource: App\Controller\MoviesController

put_movie:
    path: /movie
    methods: [PUT]
    defaults:
        _controller: App\Controller\MoviesController:putMovieAction
        _format: json